#!/bin/bash

# ANSI escape codes for printf
# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37

BLUE='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
ORANGE='\033[0;33m'
YELLOW='\033[1;33m'
NC='\033[0m'
BLACK='\033[0;30m'

user=$(whoami)
current_dir=$(pwd)
package_dir=$(echo $current_dir/pkgs.txt)
custom_dir=$(echo $current_dir/custom.txt)

main () {
  print_logo
  read_packages
  read_custom
  install_packages
  install_custom
}

print_help () {
  echo -e "Welcome to the ${GREEN}ZimOS${NC} installation script"
  echo ""
  echo This expects you to:
  echo -e "- be running an ${BLUE}ARCH${NC} based distro"
  echo -e "- have ${RED}pkgs.txt${NC} in the directory you run this script from"
  echo -e "- have ${RED}custom.txt${NC} in the directory you run this script from"
  echo ""
  echo "Usage: ./zimos.sh [OPTION]"
  echo "Example: './zimos.sh i'"
  echo "OPTIONS: "
  echo "    -i, --install, i, install         Install packages from files"
  echo "    -u, --uninstall, u, uninstall     Uninstall packages from files"
  echo "    -h, --help, h, help               Print this help"
  echo ""
  echo "N.B. This is a minimal install to have a working Desktop Environment"
  echo "     although it can be extended through the packages"
}

pac_install () {
  sudo pacman -Sy --needed --noconfirm $@
  echo $@
}

print_logo () {
  printf "\n"
  COLUMNS=$(tput cols) 
  line1=" oooooooooooo ooooo ooo        ooooo   .oooooo.    .oooooo..o "
  line2="d'\"\"\"\"\"\"d888' \`888' \`88.       .888'  d8P'  \`Y8b  d8P'    \`Y8 "
  line3="      .888P    888   888b     d'888  888      888 Y88bo.      "
  line4="     d888'     888   8 Y88. .P  888  888      888  \`\"Y8888o.  "
  line5="   .888P       888   8  \`888'   888  888      888      \`\"Y88b "
  line6="  d888'    .P  888   8    Y     888  \`88b    d88' oo     .d8P "
  line7=".8888888888P  o888o o8o        o888o  \`Y8bood8P'  8\"\"88888P'  "
  printf "${GREEN}%*s\n" $(((${#line1}+$COLUMNS)/2)) "$line1"
  printf "${YELLOW}%*s\n" $(((${#line2}+$COLUMNS)/2)) "$line2"
  printf "${RED}%*s\n" $(((${#line2}+$COLUMNS)/2)) "$line3"
  printf "${BLACK}%*s\n" $(((${#line2}+$COLUMNS)/2)) "$line4"
  printf "${RED}%*s\n" $(((${#line2}+$COLUMNS)/2)) "$line5"
  printf "${YELLOW}%*s\n" $(((${#line2}+$COLUMNS)/2)) "$line6"
  printf "${GREEN}%*s\n" $(((${#line2}+$COLUMNS)/2)) "$line7"
  printf "${NC}\n"
}


read_packages () {
  readarray -t packages < $package_dir
}

read_custom () {
  readarray -t custom < $custom_dir
}

install_packages () {
  echo -e "Installing Packages from ${RED}$package_dir${NC}"
  pac_install ${packages[*]}
}

install_custom () {
  source ./custom.sh
  echo -e "Installing Custom Packages from ${RED}$custom_dir${NC}"
  custom_packages
}

uninstall () {
  read_custom
  read_packages
  echo uninstalling
  sudo pacman -R ${packages[*]}
}

if [ $# -gt 0 ]; then
  case "$1" in
    -h | help | --help | h) print_help ; shift ;;
    -i | --install | install | i) main "$@" ; shift ;;
    -u | --uninstall | uninstall | u) uninstall ; shift ;;
    *) print_help ; shift ;;
  esac
else
  print_help
fi
